### ISSUE TITLE
Missing typings dependency?

### ISSUE THREAD

**Issue by retallicka** [BioPhoton/angular1-star-rating#40]
Using 1.0.15 I got

```
> typings install

sh: typings: command not found
```

So to fix this I had to do

`npm install typings --global`

then it worked

**Comment by BioPhoton** [comment]
What do you mean? I guess you just need this if you try to build it on your machine not when loading it from npm right?

Should i add this in the docs under a dev section?

**Comment by retallicka** [comment]
@BioPhoton I did load it from npm to use in my project :) I think maybe `typings install` should be first, but I'm not sure

**Comment by BioPhoton** [comment]
Thx. I released a new version. Many new features included. I also readme updated.
Its version 1.1.0 :-)
