### ISSUE TITLE
"npm i angular-star-rating" fails-installing the package if no "typings" module installed locally or globally

### ISSUE THREAD

**Issue by rajahu** [BioPhoton/angular1-star-rating#42]
"npm i angular-star-rating" fails-installing the package if no "typings" module installed locally or globally, just because, "npm postinstall" hook for the project says "typings install". I think that is required from project building prespective as it's written in 'typescript', but again this is something related to building the project itself and should be moved somewhere else out of "npm postinstall" hook, which even gets triggered if package being installed via npm.

As of now quick fix would be to add "typings" as "devDependency", so that at least we get this package installed, but then again it shows a "Warning Message : typings WARN enoent Path "\node_modules\angular-star-rating\typings.json" is missing", as "typings.json" is again something related to project internally(added to .npmignore) and thus does not get included when project being downloaded via npm.

**Comment by BioPhoton** [comment]
Hi @rajahu. Thanks for your post. 

I will remove the postinstall script as there are no other dependecies installed that need typings.

**Comment by BioPhoton** [comment]
hey @rajahu, 
there is a new version available. I implemented your suggestions. :-)

Thanks again for investigating time.

**Comment by rajahu** [comment]
You're welcome :) !
