### ISSUE TITLE
WARNING: Tried to load angular more than once

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/angular1-star-rating#51]
This issue is created based on [this comment](https://github.com/BioPhoton/angular1-star-rating/issues/44#issuecomment-277016464). 

I guess this is a build problem.

**Comment by Lennaert** [comment]
Now I'm getting "`Uncaught ReferenceError: require is not defined`" in Chrome 55 on MacOS.

**Comment by BioPhoton** [comment]
Ok, now its fixed in version 1.2.9. If there is sill a problem you can reopen the issue...
