### ISSUE TITLE
Value not changing on Hover 

### ISSUE THREAD

**Issue by tejasrivastav** [BioPhoton/angular1-star-rating#55]
![Image of readme](https://raw.githubusercontent.com/BioPhoton/angular1-star-rating/master/resources/example-usage.gif)

As shown in the image the value of the star comp changes on mouser over of the star and value is set on click.
But the default behaviour is not the same.

Any config/ workaround to achieve it ..?

**Comment by BioPhoton** [comment]
Hi @tejasrivastav ,  these are no hovers but clicks! In the css version is this feature aleardy implemented. So it is easy to implement it here too. You could do a PR. 😁

Otherwise I can implement this in about 3 weeks.

Thanks for commenting!
