### ISSUE TITLE
WARNING: tried to load angular more than once

### ISSUE THREAD

**Issue by warjohn123** [BioPhoton/angular1-star-rating#67]
I'm currently using Fuse Angular Material JS boilerplate and when I'm adding this:
<script src="https://cdn.rawgit.com/BioPhoton/angular1-star-rating/v1.2.4/dist/index.js"></script>

to my index.html, it gets "WARNING: tried to load angular more than once:

**Comment by BioPhoton** [comment]
Hi! Thanks for your feedback.
Try to install the latest version. It should work.

Best Michael

**Comment by warjohn123** [comment]
I currently have version 1.2.11 and it's not working :(

**Comment by BioPhoton** [comment]
What is the problem? Could you give me some error logs or so?

Thanks!
